# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: glt
    ports:
      - ${DB_PORT}:${DB_PORT}

  adminer:
    image: adminer
    restart: always
    ports:
      - 9002:8080
      
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: sh -c "/wait && /root/dist/DbCreator && /root/dist/glt"
    environment:
      - WAIT_HOSTS=db:${DB_PORT}
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30